# Generated by Django 3.2.9 on 2021-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cissuer', models.CharField(max_length=50)),
                ('creceiver', models.CharField(max_length=50)),
                ('cgivendate', models.DateField()),
                ('cexpirydate', models.DateField()),
                ('crenewalteam', models.CharField(max_length=50)),
                ('cstatus', models.CharField(max_length=20)),
            ],
        ),
    ]
